#!/bin/sh

# This script runs before "git commit". Can be bypassed with the "git commit --no-verify" option.
# Checks if any of the changed files are .py files; if so, run the linter on them.
echo "Running hooks/pre-commit..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")
[ -z "$STAGED_FILES" ] && exit 0

# Run flake8
python -m flake8 $STAGED_FILES
exit $?
