#!/bin/sh

# This script runs before "git commit". Can be bypassed with the "git commit --no-verify" option.
# Checks if any of the changed files are .py files; if so, run the linter on them.
echo "Running hooks/pre-commit..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")
[ -z "$STAGED_FILES" ] && exit 0

# Check if the linter is installed
if ! command -v python -m flake8 >/dev/null 2>&1; then
    echo "Install flake8 with 'pip install flake8' before committing."
    exit 1
fi

# Run flake8
python -m flake8 $STAGED_FILES
exit $?
